import Link from "next/link";
import { ArrowRight, BadgeCheck, CheckCircle2, Dumbbell, Search, ShieldCheck, Users } from "lucide-react";
import { Card } from "@/components/ui";
import { Nav } from "@/components/nav";
const roles = ["Athletes", "Coaches", "Support staff", "Officials", "Scouts", "Clubs"];
export default function Home() { return <><Nav/><main><section className="container-page grid gap-12 py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div><p className="eyebrow"><BadgeCheck size={14}/> India&apos;s sports professional network</p><h1 className="mt-5 font-heading text-4xl font-extrabold leading-tight sm:text-6xl">Your sporting journey deserves a <span className="text-accent">stronger</span> network.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Build a professional profile, celebrate your work and connect with the people moving Indian sport forward.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 font-bold text-white shadow-sm">Register free <ArrowRight size={17}/></Link><a href="#how" className="rounded-lg border px-5 py-3 font-bold">See how it works</a></div><div className="mt-10 flex gap-7"><Stat value="10K+" label="Sporting voices"/><Stat value="28" label="States connected"/><Stat value="100%" label="Free to join"/></div></div><ProfilePreview/></section><section className="border-y bg-surface py-8"><div className="container-page flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm font-bold text-slate-600">{roles.map((role) => <span key={role}>{role}</span>)}</div></section><section id="how" className="container-page py-20"><div className="max-w-xl"><p className="eyebrow">Simple by design</p><h2 className="mt-4 font-heading text-3xl font-extrabold">Take your place in the game.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Step icon={<ShieldCheck/>} num="01" title="Create your profile" text="Tell the community about your role, sports, and experience."/><Step icon={<Dumbbell/>} num="02" title="Build your profile" text="Show your role, sports, experience and achievements."/><Step icon={<Search/>} num="03" title="Get discovered" text="Be ready when the right opportunity comes along."/></div></section><section className="container-page pb-20"><div className="rounded-2xl bg-foreground px-7 py-12 text-center text-white sm:px-14"><h2 className="font-heading text-3xl font-extrabold">The next play starts with you.</h2><p className="mx-auto mt-3 max-w-lg text-slate-300">Join the growing professional network built for Indian sport.</p><Link href="/login" className="mt-7 inline-flex rounded-lg bg-accent px-5 py-3 font-bold">Create your profile</Link></div></section></main><footer className="border-t py-7 text-center text-sm text-slate-500">© {new Date().getFullYear()} BharatKheloSetu · Built for Indian sport</footer></> }
function Stat({value,label}:{value:string;label:string}) { return <div><p className="font-heading text-2xl font-extrabold text-primary">{value}</p><p className="text-xs text-slate-500">{label}</p></div> }
function Step({icon,num,title,text}:{icon:React.ReactNode;num:string;title:string;text:string}) { return <Card className="p-6"><div className="flex items-center justify-between text-primary">{icon}<span className="font-heading font-bold text-slate-300">{num}</span></div><h3 className="mt-5 font-heading text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></Card> }
function ProfilePreview() { return <Card className="overflow-hidden self-center"><div className="h-20 bg-primary"/><div className="-mt-10 px-6 pb-6"><div className="grid h-20 w-20 place-items-center rounded-2xl border-4 border-white bg-orange-100 font-heading text-2xl font-bold text-accent">AS</div><div className="mt-3 flex items-start justify-between"><div><h3 className="font-heading text-xl font-bold">Aarav Singh</h3><p className="text-sm text-slate-500">Footballer · Bengaluru</p></div><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-bold text-success">Available</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Tile value="8" label="Years"/><Tile value="34" label="Matches"/><Tile value="12" label="Goals"/></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">Profile strength</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[82%] rounded-full bg-accent"/></div><div className="mt-4 flex gap-2"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-primary">Football</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">Midfielder</span></div></div></Card> }
function Tile({value,label}:{value:string;label:string}) { return <div className="rounded-lg bg-surface py-2"><b className="block font-heading">{value}</b><span className="text-[10px] text-slate-500">{label}</span></div> }
