"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { doc, getDoc } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { auth, db } from "@/lib/firebase";
import type { Profile } from "@/lib/profile";
import { Button, Card } from "@/components/ui";
import { Nav } from "@/components/nav";
import { MapPin, Pencil, ShieldCheck } from "lucide-react";
export default function ProfilePage(){const router=useRouter();const [profile,setProfile]=useState<Profile>();useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){router.replace("/login");return;}const snap=await getDoc(doc(db,"users",u.uid));if(!snap.exists()){router.replace("/join");return;}setProfile(snap.data() as Profile)}),[router]);if(!profile)return <><Nav/><main className="container-page py-16 text-center text-slate-500">Loading your profile…</main></>;return <><Nav/><main className="container-page py-10"><Card className="overflow-hidden"><div className="h-28 bg-primary"/><div className="px-6 pb-6"><div className="-mt-12 grid h-24 w-24 place-items-center rounded-2xl border-4 border-white bg-orange-100 font-heading text-3xl font-bold text-accent">{profile.fullName.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div className="mt-4 flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex items-center gap-2"><h1 className="font-heading text-3xl font-extrabold">{profile.fullName}</h1><ShieldCheck className="text-primary" size={20}/></div><p className="mt-1 font-semibold text-slate-600">{profile.primaryRole} · {profile.sports.join(", ")||"Sport professional"}</p><p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><MapPin size={15}/>{profile.city}, {profile.state}</p></div><Link href="/onboarding/profile"><Button className="gap-2"><Pencil size={16}/> Edit profile</Button></Link></div>{profile.bio&&<p className="mt-6 max-w-2xl leading-7 text-slate-600">{profile.bio}</p>}<div className="mt-7 grid gap-5 border-t pt-6 md:grid-cols-[1fr_2fr]"><div><p className="font-heading text-lg font-bold">Profile completion</p><p className="mt-1 text-sm text-slate-500">Complete profiles get discovered faster.</p></div><div><div className="flex justify-between text-sm font-bold"><span>{profile.profileCompletionPct}% complete</span><span className="text-success">Active</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-surface"><div className="h-full rounded-full bg-accent" style={{width:`${profile.profileCompletionPct}%`}}/></div></div></div></div></Card><div className="mt-6 grid gap-5 md:grid-cols-2"><Card className="p-6"><h2 className="font-heading text-lg font-bold">Role details</h2><dl className="mt-4 space-y-3 text-sm">{Object.entries(profile.roleDetails).filter(([,v])=>v).map(([k,v])=><div key={k} className="flex justify-between gap-4"><dt className="capitalize text-slate-500">{k.replace(/([A-Z])/g," $1")}</dt><dd className="font-semibold text-right">{v}</dd></div>)}</dl></Card><Card className="p-6"><h2 className="font-heading text-lg font-bold">Achievements</h2>{profile.achievements.length?<ul className="mt-4 space-y-2 text-sm text-slate-600">{profile.achievements.map((a,i)=><li key={i}>• {a}</li>)}</ul>:<p className="mt-4 text-sm text-slate-500">Add achievements to strengthen your profile.</p>}</Card></div></main></>}
