"use client";
import { useEffect, useRef, useState } from "react";
import { ConfirmationResult, RecaptchaVerifier, signInWithPhoneNumber } from "firebase/auth";
import { useRouter } from "next/navigation";
import { doc, getDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { Button, Card, Input } from "@/components/ui";
import { Nav } from "@/components/nav";
export default function Login() { const router = useRouter(); const [phone,setPhone]=useState(""); const [code,setCode]=useState(""); const [confirm,setConfirm]=useState<ConfirmationResult>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const verifier=useRef<RecaptchaVerifier>();
 useEffect(()=>{ verifier.current = new RecaptchaVerifier(auth, "recaptcha", { size: "invisible" }); return ()=>verifier.current?.clear(); },[]);
 async function sendCode(){ setError(""); if(!/^\d{10}$/.test(phone)){setError("Enter a valid 10-digit Indian mobile number.");return;} setBusy(true); try { setConfirm(await signInWithPhoneNumber(auth, `+91${phone}`, verifier.current!)); } catch { setError("We couldn’t send your code. Please try again."); } finally {setBusy(false);} }
 async function verify(){ if(code.length!==6||!confirm)return; setBusy(true);setError("");try { const credential=await confirm.confirm(code); const existing=await getDoc(doc(db,"users",credential.user.uid)); router.push(existing.exists() && existing.data().profileComplete ? "/profile" : "/join"); } catch {setError("That code is invalid or has expired.");}finally{setBusy(false);} }
 return <><Nav/><main className="container-page grid min-h-[calc(100vh-64px)] place-items-center py-10"><Card className="w-full max-w-md p-6 sm:p-8"><p className="eyebrow">Secure sign in</p><h1 className="mt-4 font-heading text-3xl font-extrabold">Welcome to the network.</h1><p className="mt-2 text-sm leading-6 text-slate-600">Use your mobile number. No passwords, ever.</p>{!confirm ? <div className="mt-7"><label className="label">Mobile number</label><div className="mt-1 flex rounded-lg border focus-within:border-primary focus-within:ring-2 focus-within:ring-blue-100"><span className="flex items-center border-r px-3 text-sm font-bold">+91</span><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" placeholder="98765 43210" className="min-w-0 flex-1 rounded-r-lg px-3 py-2.5 outline-none"/></div><Button className="mt-5 w-full" disabled={busy} onClick={sendCode}>{busy?"Sending…":"Send OTP"}</Button></div> : <div className="mt-7"><label className="label">Enter the 6-digit code</label><Input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" maxLength={6} placeholder="••••••" className="mt-2 text-center text-2xl tracking-[.5em]"/><Button className="mt-5 w-full" disabled={busy||code.length!==6} onClick={verify}>{busy?"Verifying…":"Verify & continue"}</Button><button className="mt-3 w-full text-sm font-bold text-primary" onClick={()=>setConfirm(undefined)}>Use another number</button></div>}<div id="recaptcha"/>{error&&<p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}</Card></main></> }
