"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { auth, db } from "@/lib/firebase";
import { getCompletion, roles, roleFields, type Role } from "@/lib/profile";
import { Button, Card, Input } from "@/components/ui";
import { Nav } from "@/components/nav";
export default function Onboarding(){const router=useRouter(); const [role,setRole]=useState<Role>("Athlete");const [userId,setUserId]=useState("");const [phone,setPhone]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false); const [form,setForm]=useState<Record<string,string>>({fullName:"",dob:"",gender:"",city:"",state:"",sports:"",photoURL:"",bio:"",preferredLanguage:"English",achievements:"",instagram:"",twitter:"",youtube:"",linkedin:""}); const [details,setDetails]=useState<Record<string,string>>({});const [consent,setConsent]=useState(false);
useEffect(()=>{const selected=(sessionStorage.getItem("selectedRole") as Role);if(selected)setRole(selected);return onAuthStateChanged(auth,async u=>{if(!u){router.replace("/login");return;}setUserId(u.uid);setPhone(u.phoneNumber||"");const existing=await getDoc(doc(db,"users",u.uid));if(existing.exists()){const p=existing.data() as Record<string, any>;setRole(p.primaryRole);setForm(v=>({...v,fullName:p.fullName||"",dob:p.dob||"",gender:p.gender||"",city:p.city||"",state:p.state||"",sports:(p.sports||[]).join(", "),photoURL:p.photoURL||"",bio:p.bio||"",preferredLanguage:p.preferredLanguage||"English",achievements:(p.achievements||[]).join("\n"),...(p.socialLinks||{})}));setDetails(p.roleDetails||{});setConsent(Boolean(p.consent?.given));}})},[router]); const update=(k:string,v:string)=>setForm(p=>({...p,[k]:v}));
async function submit(e:FormEvent){e.preventDefault();setError(""); const age=(Date.now()-new Date(form.dob).getTime())/31557600000;if(!form.fullName||!form.dob||age<18||!form.gender||!form.city||!form.state||!consent){setError(age<18?"You must be 18 or older to create a profile.":"Complete the required fields and consent to continue.");return;} setSaving(true);const sports=form.sports.split(",").map(s=>s.trim()).filter(Boolean);const pct=getCompletion({fullName:form.fullName,dob:form.dob,gender:form.gender,city:form.city,state:form.state,primaryRole:role,sports});await setDoc(doc(db,"users",userId),{phone,fullName:form.fullName,email:"",dob:form.dob,gender:form.gender,city:form.city,state:form.state,country:"IN",sports,primaryRole:role,roleDetails:details,photoURL:form.photoURL,bio:form.bio.slice(0,500),preferredLanguage:form.preferredLanguage,socialLinks:{instagram:form.instagram,twitter:form.twitter,youtube:form.youtube,linkedin:form.linkedin},achievements:form.achievements.split("\n").map(a=>a.trim()).filter(Boolean).slice(0,10),consent:{given:true,timestamp:new Date().toISOString()},profileVisible:false,profileComplete:true,profileCompletionPct:pct,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});router.push("/profile");}
return <><Nav/><main className="container-page max-w-3xl py-10"><p className="eyebrow">Step 2 of 2 · {role}</p><h1 className="mt-4 font-heading text-3xl font-extrabold">Build your professional profile.</h1><form onSubmit={submit} className="mt-8 space-y-5"><Section title="Photo"><Field label="Photo URL" value={form.photoURL} onChange={v=>update("photoURL",v)} placeholder="https://…"/></Section><Section title="Basic information"><Grid><Field label="Full name *" value={form.fullName} onChange={v=>update("fullName",v)}/><Field label="Date of birth *" type="date" value={form.dob} onChange={v=>update("dob",v)}/><Select label="Gender *" value={form.gender} onChange={v=>update("gender",v)} options={["Female","Male","Non-binary","Prefer not to say"]}/><Field label="City *" value={form.city} onChange={v=>update("city",v)}/><Field label="State *" value={form.state} onChange={v=>update("state",v)}/><Field label="Sports (comma separated)" value={form.sports} onChange={v=>update("sports",v)} placeholder="Football, Athletics"/><Select label="Preferred language" value={form.preferredLanguage} onChange={v=>update("preferredLanguage",v)} options={["English","Hindi","Bengali","Tamil","Telugu","Marathi"]}/></Grid><label className="label mt-4 block">Bio <span className="font-normal text-slate-400">(500 characters)</span><textarea className="field h-24 resize-none" maxLength={500} value={form.bio} onChange={e=>update("bio",e.target.value)}/></label></Section><Section title={`${role} details`}><Grid>{roleFields[role].map(f=><Field key={f.key} label={`${f.label}${f.required?" *":""}`} value={details[f.key]||""} onChange={v=>setDetails(p=>({...p,[f.key]:v}))}/>)}</Grid></Section><Section title="Achievements"><textarea className="field h-24 resize-none" value={form.achievements} onChange={e=>update("achievements",e.target.value)} placeholder="One achievement per line (up to 10)"/></Section><Section title="Social links"><Grid>{["instagram","twitter","youtube","linkedin"].map(k=><Field key={k} label={k[0].toUpperCase()+k.slice(1)} value={form[k]} onChange={v=>update(k,v)} placeholder="https://"/>)}</Grid></Section><label className="flex gap-3 rounded-lg bg-surface p-4 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>I confirm that I am 18 or older and consent to BharatKheloSetu storing my profile information to provide this service.</span></label>{error&&<p className="text-sm font-semibold text-red-600">{error}</p>}<Button disabled={saving} type="submit">{saving?"Saving…":"Save profile"}</Button></form></main></>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <Card className="p-5"><h2 className="font-heading text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></Card>};function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>};function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="label">{label}<Input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>};function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="label">{label}<select className="field" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
